/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0 */

#include "sf_msgs.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GNSS, GNSS, AUTO)


PB_BIND(Data1D, Data1D, AUTO)


PB_BIND(Data2D, Data2D, AUTO)


PB_BIND(Data3D, Data3D, AUTO)


PB_BIND(Data4D, Data4D, AUTO)


PB_BIND(Data6D, Data6D, AUTO)


PB_BIND(DataND, DataND, AUTO)


PB_BIND(DataCellRss, DataCellRss, AUTO)


PB_BIND(DataBleRss, DataBleRss, AUTO)


PB_BIND(DataWifiRss, DataWifiRss, AUTO)


PB_BIND(ReccoRss, ReccoRss, AUTO)


PB_BIND(TempPhCond, TempPhCond, AUTO)


PB_BIND(WrapperData, WrapperData, 2)






